jwt:
  time: 1111
  secret: cafe~
cafe:
  name: cafe config
  count: 20
  datasource:
    url: jdbc:mysql://localhost:?.?.?.?:3306/cafe?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
spring:
  datasource:
    url: jdbc:mysql://localhost:?.?.?.?:3306/cafe?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
#    password: '{cipher}da48a70f34e73581993e271b9ee39a5a0d877c228d06bca69b90bf92dc688046'