jwt:
  time: 1111
  secret: boardr~
cafe:
  name: boardr config
  count: 20
  datasource:
    url: jdbc:mysql://localhost:?.?.?.?:3306/cafe?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

# 토큰 설정
token:
  expiration_time: 86400000
  secret: userToken_userToken_userToken_userToken_userToken_userToken_userToken_userToken_userToken_userToken_userToken_userToken_userToken_userToken_userToken_userToken_
